export const CREATE_SOP = "CREATE_SOP";
export const LOAD_SOPS_SUCCES = "LOAD_SOPS_SUCCES";

export const CREATE_DEVICE = "CREATE_DEVICE";
export const LOAD_DEVICES_SUCCES = "LOAD_DEVICES_SUCCES";
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
