export const CREATE_SOP = "CREATE_SOP";
export const LOAD_SOPS_SUCCES = "LOAD_SOPS_SUCCES";
export const CREATE_SOP_SUCCESS = "CREATE_SOP_SUCCESS";
export const UPDATE_SOP_SUCCESS = "UPDATE_SOP_SUCCESS";

export const CREATE_DEVICE = "CREATE_DEVICE";
export const LOAD_DEVICES_SUCCES = "LOAD_DEVICES_SUCCES";
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCES";
